---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-safe-maxpods-role
  labels:
    app: kube-safe-maxpods
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["*"]

- apiGroups: ["*"]
  resources: ["deployments"]
  resourceNames: ["kube-safe-maxpods"]
  verbs: ["get"]

- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-safe-maxpods
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-safe-maxpods-role-binding
subjects:
  - kind: ServiceAccount
    name: kube-safe-maxpods
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-safe-maxpods-role
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-safe-maxpods
  name: kube-safe-maxpodcount
  namespace: kube-system
spec:
  ports:
    - port: 443
  selector:
    app: kube-safe-maxpods
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-safe-maxpods
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-safe-maxpods
    spec:
      serviceAccountName: kube-safe-maxpods
      containers:
      - name: kube-safe-maxpods
        image: docker.io/emblica/kube-safe-maxpods:0.1
        args:
        - "-logtostderr=true"
        - "-v=1"
